language: node_js
node_js:
  - node
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - npm install -g node-qunit-phantomjs
script:
  - "node-qunit-phantomjs webapp/test/unit/unitTests.qunit.html"