language: node_js
node_js:
  - node
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - pwd 
  - "phantomjs webapp/test/phantomjs-test.js"  
  addons:
  browserstack:
    username: "andyprier1"
    access_key: "fJK5ps6VBd9tSgwU6dn9"